# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166fFM2YEfduz2WG8mErpcHJdJJyGR2p3
"""

import requests
import json
import os

def check_inventory_status():
  target_url = "https://www.costco.com.tw/rest/v2/taiwan/products/158005/?fields=FULL&lang=zh_TW&curr=TWD"
  stock_message = ""
  headers = {
    "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"
    }

  print("開始爬取: {target_url}")
  try:
    response = requests.get(target_url, headers=headers)

    if response.status_code == 200:
      #print("--- 請求成功 (Status 200 OK) ---")

      response.encoding = "utf-8"
      product_data = response.json()
      #print("--- 成功解析產品 JSON 數據 ---")

      stockStatus = product_data.get("stock", [{}]).get("stockLevelStatus", [])
      print(stockStatus)

      if stockStatus == "inStock":
        stock_message = "有現貨"
        return stock_message

      else:
        stock_message = "缺貨中"
        return stock_message


  except requests.exceptions.RequestException as e:
    return f"請求失敗: {e}"


def check_inventory_and_notify():
  buy_url = "https://www.costco.com.tw/Digital-Mobile/Mobile-Tablets/iPhone-Mobile-Phones/Apple-iPhone-17-256GB-Black/p/158005"
  TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
  chat_id = os.environ.get("TELEGRAM_CHAT_ID")
  print(f"TOKEN read success: {bool(TOKEN)}")
  print(f"CHAT_ID read success: {bool(chat_id)}")
  url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"

  inventory_status = check_inventory_status()

  if inventory_status == "有現貨":
    print("有貨")
    payload = {"chat_id": chat_id, "text": f"🚨有現貨!!!快去買🚨 {buy_url}"}
    response = requests.post(url=url, json=payload)
    print(f"Telegram API Status: {response.status_code}")
    print(f"Telegram API Response: {response.text}")

    return "通知送出!有貨", 200

  else:
    print("沒貨")
    payload = {"chat_id": chat_id, "text": f"缺貨中...再等等 {buy_url}"}
    response = requests.post(url=url, json=payload)
    print(f"Telegram API Status: {response.status_code}")
    print(f"Telegram API Response: {response.text}")

    return "通知送出!沒貨", 200


if __name__ == "__main__":
  check_inventory_and_notify()
  print("Crawler finished successfully.")
