# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166fFM2YEfduz2WG8mErpcHJdJJyGR2p3
"""

import requests
import json
import os

def check_inventory_status():
  target_url = "https://www.costco.com.tw/rest/v2/taiwan/products/158005/?fields=FULL&lang=zh_TW&curr=TWD"
  stock_message = ""
  headers = {
    "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"
    }

  print("開始爬取: {target_url}")
  try:
    response = requests.get(target_url, headers=headers)

    if response.status_code == 200:
      #print("--- 請求成功 (Status 200 OK) ---")

      response.encoding = "utf-8"
      product_data = response.json()
      #print("--- 成功解析產品 JSON 數據 ---")

      options = product_data.get("baseOptions", [{}])[0].get("selected", [])

      print(options["stock"]["stockLevelStatus"])

      if options["stock"]["stockLevelStatus"] == "inStock":
        stock_message = "有現貨"
        return stock_message

      else:
        stock_message = "缺貨中"
        return stock_message


  except requests.exceptions.RequestException as e:
    return f"請求失敗: {e}"


def check_inventory_and_notify():
  TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
  chat_id = os.environ.get("TELEGRAM_CHAT_ID")
  url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"

  inventory_status = check_inventory_status()

  if inventory_status == "有現貨":
    payload = {"chat_id": chat_id, "text": "🚨有現貨!!!快去買🚨"}
    response = requests.post(url=url, json=payload)

    return "通知送出!有貨", 200

  else:
    payload = {"chat_id": chat_id, "text": "缺貨中...再等等"}
    response = requests.post(url=url, json=payload)

    return "通知送出!沒貨", 200


if __name__ == "__main__":
  check_inventory_and_notify():
  print("Crawler finished successfully.")